kind: pipeline
name: default

steps:
- name: docker-pull
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  environment:
    IMAGE_NAME: wipac/monitoring-scripts
    DOCKERHUB_USER:
      from_secret: DOCKERHUB_USER
    DOCKERHUB_PASS:
      from_secret: DOCKERHUB_PASS
  commands:
  - export TAG="${DRONE_TAG:=latest}"
  - docker pull $IMAGE_NAME:latest || echo "first build"
  - docker build -t $IMAGE_NAME:$TAG
  - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
  - docker push $IMAGE_NAME:$TAG

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock